In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

# Data processing

In [3]:
df = pd.read_csv('data/Churn_Modelling.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [4]:
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

In [5]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [6]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [7]:
#----------------
# Encoding Gender
#----------------

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [8]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [10]:
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')

In [11]:
X = ct.fit_transform(X)
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [12]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [14]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Train the Model

## ANN

In [15]:
ann = tf.keras.models.Sequential()

ann.add(tf.keras.layers.Dense(units = 9, activation = 'relu'))

ann.add(tf.keras.layers.Dense(units = 9, activation = 'relu'))

ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 466us/step - accuracy: 0.7404 - loss: 0.6107
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.7909 - loss: 0.4737
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.8144 - loss: 0.4200
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 419us/step - accuracy: 0.8263 - loss: 0.4081
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.8354 - loss: 0.3959
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 422us/step - accuracy: 0.8463 - loss: 0.3791
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.8502 - loss: 0.3742
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 420us/step - accuracy: 0.8525 - loss: 0.3649
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.8547 - loss: 0.3529
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.8590 - loss: 0.3446
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.8596 - loss: 0.3493
Epoch 12/100
250/25

In [16]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 602us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [72]:
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score

print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[1513   82]
 [ 198  207]]
0.86


In [68]:
cm = confusion_matrix(y_test, y_pred)

In [69]:
cm

array([[1513,   82],
       [ 198,  207]])

In [71]:
(cm[0, 0] + cm[1, 1]) / np.sum(cm)

np.float64(0.86)

In [76]:
cm[1, 1] / (cm[1, 1] + cm[1, 0])

np.float64(0.5111111111111111)

In [ ]:
rec = recall_score(y_test, y_pred)

0.5111111111111111

In [75]:
precision_score(y_test, y_pred)

0.7162629757785467